import { Category, CmsBlock, Product } from "./types";

export const mockProducts: Product[] = [
  {
    productId: 1001,
    categoryId: 10,
    categoryName: "Bracelets",
    productName: "Natural Amethyst Bracelet",
    productCode: "AMETHYST-BRACELET",
    slug: "natural-amethyst-bracelet-1001",
    subTitle: "Polished stone beads with sterling silver details.",
    mainImage: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1200&q=80",
    salePriceCent: 3599,
    currency: "USD",
    seoTitle: "Natural Amethyst Bracelet",
    seoDescription: "Shop a natural amethyst bracelet with a polished finish and gift-ready packaging.",
    productDetail: "A lightweight bracelet made for everyday wear, finished with careful stone selection and simple hardware.",
    shelvesFlag: true,
    publishStatus: 1
  },
  {
    productId: 1002,
    categoryId: 11,
    categoryName: "Necklaces",
    productName: "Moonstone Pendant Necklace",
    productCode: "MOONSTONE-NECKLACE",
    slug: "moonstone-pendant-necklace-1002",
    subTitle: "A minimal pendant with a soft blue flash.",
    mainImage: "https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=1200&q=80",
    salePriceCent: 4899,
    currency: "USD",
    seoTitle: "Moonstone Pendant Necklace",
    seoDescription: "A minimal moonstone pendant necklace designed for daily styling.",
    productDetail: "This pendant keeps the shape quiet and refined, with an adjustable chain for layered looks.",
    shelvesFlag: true,
    publishStatus: 1
  },
  {
    productId: 1003,
    categoryId: 12,
    categoryName: "Rings",
    productName: "Stacking Silver Ring",
    productCode: "SILVER-STACK-RING",
    slug: "stacking-silver-ring-1003",
    subTitle: "A polished silver band designed for stacking.",
    mainImage: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=80&sat=-25",
    salePriceCent: 2499,
    currency: "USD",
    seoTitle: "Stacking Silver Ring",
    seoDescription: "A polished silver stacking ring for everyday styling.",
    productDetail: "A clean, durable piece that works alone or stacked with gemstone rings.",
    shelvesFlag: true,
    publishStatus: 1
  },
  {
    productId: 1004,
    categoryId: 11,
    categoryName: "Necklaces",
    productName: "Freshwater Pearl Strand",
    productCode: "PEARL-STRAND",
    slug: "freshwater-pearl-strand-1004",
    subTitle: "Luminous freshwater pearls with a modern clasp.",
    mainImage: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=80",
    salePriceCent: 6899,
    currency: "USD",
    seoTitle: "Freshwater Pearl Strand",
    seoDescription: "A modern freshwater pearl necklace finished with a polished clasp.",
    productDetail: "Individually selected pearls create a softly luminous strand designed for celebrations and everyday tailoring.",
    shelvesFlag: true,
    publishStatus: 1
  },
  {
    productId: 1005,
    categoryId: 12,
    categoryName: "Rings",
    productName: "Sculpted Signet Ring",
    productCode: "SCULPTED-SIGNET",
    slug: "sculpted-signet-ring-1005",
    subTitle: "A softly rounded statement ring in polished silver.",
    mainImage: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=80",
    salePriceCent: 4299,
    currency: "USD",
    seoTitle: "Sculpted Signet Ring",
    seoDescription: "A polished sculptural signet ring made for everyday wear.",
    productDetail: "A weighty but comfortable silhouette, polished by hand for a mirror-like finish.",
    shelvesFlag: true,
    publishStatus: 1
  },
  {
    productId: 1006,
    categoryId: 10,
    categoryName: "Bracelets",
    productName: "Golden Chain Bracelet",
    productCode: "GOLDEN-CHAIN",
    slug: "golden-chain-bracelet-1006",
    subTitle: "Fine interlocking links with an adjustable finish.",
    mainImage: "https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=1200&q=80",
    salePriceCent: 5299,
    currency: "USD",
    seoTitle: "Golden Chain Bracelet",
    seoDescription: "A fine golden chain bracelet with an adjustable clasp.",
    productDetail: "Light-catching links and an adjustable clasp make this an easy piece to stack or wear alone.",
    shelvesFlag: true,
    publishStatus: 1
  },
  {
    productId: 1007,
    categoryId: 13,
    categoryName: "Earrings",
    productName: "Pearl Drop Earrings",
    productCode: "PEARL-DROP",
    slug: "pearl-drop-earrings-1007",
    subTitle: "Balanced pearl drops with a clean contemporary line.",
    mainImage: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=1200&q=80",
    salePriceCent: 3899,
    currency: "USD",
    seoTitle: "Pearl Drop Earrings",
    seoDescription: "Contemporary pearl drop earrings for effortless day-to-evening styling.",
    productDetail: "A clean drop silhouette gives softly irregular pearls an architectural setting.",
    shelvesFlag: true,
    publishStatus: 1
  },
  {
    productId: 1008,
    categoryId: 13,
    categoryName: "Earrings",
    productName: "Mini Crystal Hoops",
    productCode: "CRYSTAL-HOOPS",
    slug: "mini-crystal-hoops-1008",
    subTitle: "Compact hoops with a precise row of clear stones.",
    mainImage: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=1200&q=80",
    salePriceCent: 2999,
    currency: "USD",
    seoTitle: "Mini Crystal Hoops",
    seoDescription: "Small crystal hoops designed for comfortable all-day wear.",
    productDetail: "A refined scale, secure closure, and just enough light make these a daily favorite.",
    shelvesFlag: true,
    publishStatus: 1
  },
  {
    productId: 1009,
    categoryId: 20,
    categoryName: "Intimates",
    productName: "Noir Satin Camisole Set",
    productCode: "NOIR-CAMISOLE-SET",
    slug: "noir-satin-camisole-set-1009",
    subTitle: "Fluid satin, fine lace, and an easy adjustable fit.",
    mainImage: "/images/storefront/intimates-still-life.png",
    salePriceCent: 6899,
    currency: "USD",
    seoTitle: "Noir Satin Camisole Set",
    seoDescription: "A refined black satin camisole set finished with delicate lace.",
    productDetail: "A softly structured camisole and short pairing designed for evening dressing and slow mornings.",
    shelvesFlag: true,
    publishStatus: 1
  },
  {
    productId: 1010,
    categoryId: 20,
    categoryName: "Intimates",
    productName: "Ivory Line Camisole",
    productCode: "IVORY-LINE-CAMISOLE",
    slug: "ivory-line-camisole-1010",
    subTitle: "Clean ivory satin with a softly draped neckline.",
    mainImage: "/images/storefront/intimates-editorial.png",
    salePriceCent: 5299,
    currency: "USD",
    seoTitle: "Ivory Line Camisole",
    seoDescription: "An ivory satin camisole with a clean, versatile silhouette.",
    productDetail: "Cut to move from first layer to evening top, with adjustable straps and a fluid hand.",
    shelvesFlag: true,
    publishStatus: 1
  },
  {
    productId: 1011,
    categoryId: 20,
    categoryName: "Intimates",
    productName: "After Dark Soft Bra",
    productCode: "AFTER-DARK-SOFT-BRA",
    slug: "after-dark-soft-bra-1011",
    subTitle: "Light support in satin and fine geometric lace.",
    mainImage: "/images/storefront/intimates-hero.png",
    salePriceCent: 5999,
    currency: "USD",
    seoTitle: "After Dark Soft Bra",
    seoDescription: "A black satin soft bra with light support and refined lace.",
    productDetail: "A wireless silhouette with adjustable straps and thoughtful seam placement for a light, natural fit.",
    shelvesFlag: true,
    publishStatus: 1
  },
  {
    productId: 1012,
    categoryId: 21,
    categoryName: "Sleepwear",
    productName: "Silk Veil Robe",
    productCode: "SILK-VEIL-ROBE",
    slug: "silk-veil-robe-1012",
    subTitle: "An ivory robe with a relaxed line and soft sheen.",
    mainImage: "/images/storefront/intimates-still-life.png",
    salePriceCent: 7499,
    currency: "USD",
    seoTitle: "Silk Veil Robe",
    seoDescription: "A light ivory robe designed for layering over intimates.",
    productDetail: "A relaxed wrap silhouette with an internal tie and a clean, lightly lustrous finish.",
    shelvesFlag: true,
    publishStatus: 1
  }
];

export const mockCategories: Category[] = [
  {
    categoryId: 20,
    categoryName: "Intimates",
    categoryCode: "intimates",
    categoryImage: "/images/storefront/intimates-hero.png",
    slug: "intimates"
  },
  {
    categoryId: 21,
    categoryName: "Sleepwear",
    categoryCode: "sleepwear",
    categoryImage: "/images/storefront/intimates-still-life.png",
    slug: "sleepwear"
  },
  {
    categoryId: 10,
    categoryName: "Bracelets",
    categoryCode: "bracelets",
    slug: "bracelets"
  },
  {
    categoryId: 11,
    categoryName: "Necklaces",
    categoryCode: "necklaces",
    slug: "necklaces"
  },
  {
    categoryId: 12,
    categoryName: "Rings",
    categoryCode: "rings",
    slug: "rings"
  },
  {
    categoryId: 13,
    categoryName: "Earrings",
    categoryCode: "earrings",
    slug: "earrings"
  }
];

export const mockCmsBlocks: CmsBlock[] = [
  {
    blockId: 7,
    blockType: 7,
    blockName: "store-announcement",
    blockTitle: "Jewelry and intimates, considered together",
    linkUrl: "/search",
    configJson: "{\"theme\":\"dark\"}",
    sort: 10
  },
  {
    blockId: 1,
    blockType: 1,
    blockName: "home-hero",
    blockTitle: "Made For Your Own Rhythm",
    blockSubTitle: "New intimates, sculptural jewelry, and pieces that move easily between private and public.",
    image: "/images/storefront/intimates-hero.png",
    linkUrl: "/collections/intimates",
    configJson: "{\"height\":\"tall\",\"textPosition\":\"left\",\"buttonText\":\"Shop new arrivals\"}",
    sort: 20
  },
  {
    blockId: 8,
    blockType: 4,
    blockName: "new-and-noted",
    blockTitle: "New and Noted",
    blockSubTitle: "The latest pieces across intimates and jewelry.",
    linkUrl: "/search",
    configJson: "{\"limit\":8,\"columns\":4,\"collectionUrl\":\"/search\"}",
    sort: 30
  },
  {
    blockId: 2,
    blockType: 2,
    blockName: "category-intimates",
    blockTitle: "Intimates",
    blockSubTitle: "Satin, lace, and first layers.",
    image: "/images/storefront/intimates-editorial.png",
    linkUrl: "/collections/intimates",
    configJson: "{\"layout\":\"grid\"}",
    sort: 40
  },
  {
    blockId: 3,
    blockType: 2,
    blockName: "category-jewelry",
    blockTitle: "Jewelry",
    blockSubTitle: "Light-catching pieces for every day.",
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1200&q=80",
    linkUrl: "/search?keyword=jewelry",
    configJson: "{\"layout\":\"grid\"}",
    sort: 50
  },
  {
    blockId: 4,
    blockType: 2,
    blockName: "category-sleepwear",
    blockTitle: "Sleepwear",
    blockSubTitle: "Soft tailoring after dark.",
    image: "/images/storefront/intimates-still-life.png",
    linkUrl: "/collections/sleepwear",
    configJson: "{\"layout\":\"grid\"}",
    sort: 60
  },
  {
    blockId: 5,
    blockType: 5,
    blockName: "first-layer-story",
    blockTitle: "The First Layer",
    blockSubTitle: "Quietly expressive pieces designed to be worn your way, from the first layer outward.",
    image: "/images/storefront/intimates-editorial.png",
    linkUrl: "/collections/intimates",
    configJson: "{\"imagePosition\":\"right\",\"buttonText\":\"Discover the edit\"}",
    sort: 70
  },
  {
    blockId: 6,
    blockType: 6,
    blockName: "evening-edit",
    blockTitle: "The Evening Edit",
    blockSubTitle: "Satin, silver, and a little more intention.",
    image: "/images/storefront/intimates-still-life.png",
    linkUrl: "/search",
    configJson: "{\"height\":\"tall\",\"buttonText\":\"Explore the edit\"}",
    sort: 80
  }
];
