-- 商城阶段6：订单管理 MVP

CREATE TABLE IF NOT EXISTS `shop_order` (
  `order_id` bigint NOT NULL AUTO_INCREMENT COMMENT '订单ID',
  `tenant_id` bigint NOT NULL DEFAULT 1 COMMENT '租户ID',
  `order_no` varchar(64) NOT NULL COMMENT '订单号',
  `customer_id` bigint DEFAULT NULL COMMENT '客户ID',
  `customer_name` varchar(100) DEFAULT NULL COMMENT '客户名称',
  `customer_email` varchar(150) DEFAULT NULL COMMENT '客户邮箱',
  `customer_phone` varchar(50) DEFAULT NULL COMMENT '客户手机',
  `country_code` varchar(20) DEFAULT NULL COMMENT '国家编码',
  `province` varchar(100) DEFAULT NULL COMMENT '省/州',
  `city` varchar(100) DEFAULT NULL COMMENT '城市',
  `address_detail` varchar(500) DEFAULT NULL COMMENT '详细地址',
  `currency` varchar(20) NOT NULL DEFAULT 'USD' COMMENT '币种',
  `product_amount_cent` bigint NOT NULL DEFAULT 0 COMMENT '商品金额，单位分',
  `freight_amount_cent` bigint NOT NULL DEFAULT 0 COMMENT '运费，单位分',
  `discount_amount_cent` bigint NOT NULL DEFAULT 0 COMMENT '优惠金额，单位分',
  `tax_amount_cent` bigint NOT NULL DEFAULT 0 COMMENT '税费，单位分',
  `payable_amount_cent` bigint NOT NULL DEFAULT 0 COMMENT '应付金额，单位分',
  `paid_amount_cent` bigint NOT NULL DEFAULT 0 COMMENT '实付金额，单位分',
  `order_status` int NOT NULL DEFAULT 1 COMMENT '订单状态：1待支付 2已确认 3已发货 4已完成 5已取消',
  `pay_status` int NOT NULL DEFAULT 1 COMMENT '支付状态：1未支付 2已支付',
  `fulfillment_status` int NOT NULL DEFAULT 1 COMMENT '发货状态：1未发货 2部分发货 3已发货',
  `refund_status` int NOT NULL DEFAULT 1 COMMENT '退款状态：1无退款 2退款中 3已退款',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消原因',
  `buyer_remark` varchar(500) DEFAULT NULL COMMENT '买家备注',
  `seller_remark` varchar(500) DEFAULT NULL COMMENT '商家备注',
  `deleted_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '删除状态',
  `create_user_id` bigint DEFAULT NULL COMMENT '创建人',
  `update_user_id` bigint DEFAULT NULL COMMENT '更新人',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `version` int NOT NULL DEFAULT 0 COMMENT '版本号',
  PRIMARY KEY (`order_id`),
  UNIQUE KEY `uk_tenant_order_no` (`tenant_id`, `order_no`),
  KEY `idx_tenant_status` (`tenant_id`, `order_status`, `pay_status`),
  KEY `idx_tenant_create_time` (`tenant_id`, `create_time`),
  KEY `idx_customer` (`customer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商城订单';

CREATE TABLE IF NOT EXISTS `shop_order_item` (
  `order_item_id` bigint NOT NULL AUTO_INCREMENT COMMENT '订单明细ID',
  `tenant_id` bigint NOT NULL DEFAULT 1 COMMENT '租户ID',
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `product_id` bigint DEFAULT NULL COMMENT '商品ID',
  `sku_id` bigint DEFAULT NULL COMMENT 'SKU ID',
  `product_name` varchar(200) NOT NULL COMMENT '商品名称快照',
  `sku_name` varchar(200) DEFAULT NULL COMMENT 'SKU名称快照',
  `sku_code` varchar(100) DEFAULT NULL COMMENT 'SKU编码快照',
  `spec_summary` varchar(500) DEFAULT NULL COMMENT '规格摘要快照',
  `product_image` varchar(500) DEFAULT NULL COMMENT '商品图片快照',
  `sale_price_cent` bigint NOT NULL DEFAULT 0 COMMENT '单价，单位分',
  `quantity` int NOT NULL DEFAULT 1 COMMENT '购买数量',
  `total_amount_cent` bigint NOT NULL DEFAULT 0 COMMENT '小计，单位分',
  `currency` varchar(20) NOT NULL DEFAULT 'USD' COMMENT '币种',
  `deleted_flag` tinyint(1) NOT NULL DEFAULT 0 COMMENT '删除状态',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`order_item_id`),
  KEY `idx_order_deleted` (`order_id`, `deleted_flag`),
  KEY `idx_product_sku` (`product_id`, `sku_id`),
  KEY `idx_tenant_order` (`tenant_id`, `order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商城订单明细';
